name: scrolling_day_calendar
description: A flutter calendar package to allow users to scroll through given dates
version: 3.0.0

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.7.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.15.2

dev_dependencies:
  flutter_test:
    sdk: flutter